hw03 done
nevian427/otus_go_homework pull request #3
Opened 2023-07-10 13:17 UTC by nevian427

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-08-01 18:07 UTC, gna69 requested changes
Без написания unit-тестов задание принято быть не может, предлагаю написать юниты

2023-08-01 18:07 UTC, gna69 commented on hw03_frequency_analysis/top.go
> +	clrSpecChr = regexp.MustCompile(`[!?;:,.'"*+<>=#%&/(){}~|\[\]\\]`)
Лучше писать полные названия переменных, так код будет проще читать. Исключением могут быть общеизвестные аббревиатуры и принятые в сообществе обозначения

2023-08-01 18:07 UTC, gna69 commented on hw03_frequency_analysis/top.go
> +	words := strings.Fields(t)
Можно оптимизировать создание мапы путем сначала разделения строки на слова, а потом передачи количества слов в мапу

2023-08-01 18:07 UTC, gna69 commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Кода для задания со звездочкой не увидел

2023-08-11 18:14 UTC, nevian427 commented on hw03_frequency_analysis/top.go
> +	clrSpecChr = regexp.MustCompile(`[!?;:,.'"*+<>=#%&/(){}~|\[\]\\]`)
переименованы

2023-08-11 18:17 UTC, nevian427 commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Ну вообще функция была написана с учётом требований под звёздочкой и тесты проходили (проверял - если включить и не обработать - валятся).
Теперь изменено под обновлённые требования и новый маленький тест прямо из ридмишки.

2023-08-14 17:46 UTC, gna69 approved these changes

2023-08-14 17:48 UTC, gna69 commented on hw03_frequency_analysis/top_test.go
> +	t.Run("positive test", func(t *testing.T) {
Название теста лучше писать так, чтобы по нему было понятно, что он проверяет

2023-08-21 12:55 UTC, merged